# Generated by Django 4.0.4 on 2022-05-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(default='review', max_length=200),
        ),
    ]
